### ISSUE TITLE
Can I run it directly？

### ISSUE THREAD

**Issue by aloof15** [danielNaczo/Python3Parser#1]

**Comment by danielNaczo** [comment]
Hey aloof15,

you can run it directly by adding the following dependency to your pom-xml in your Maven project:

```
<dependency>
   <groupId>com.github.python3parser</groupId>
   <artifactId>python3parser</artifactId>
   <version>1.0.1</version>
</dependency>
```

With the static function `ASTParser.parseModule("pathToPython3File")` you can parse every Python3-file and it will return you an abstract syntax tree (AST). With the help of the AST you can analyze, manipulate or generate Python3-Code.

I will add a more detailed README soon.

Best regards,

danielNaczo
