### ISSUE TITLE
Support for stringbased parsing input

### ISSUE THREAD

**Issue by grombo93** [danielNaczo/Python3Parser#2]
The methods provided in `ASTParser.java` are only path-based. It would be great if they support insertion of python-code directly. 
From my point of view this would mean to implement an analog method for each provided parsing-method which accepts code in form of a string directly. 
This is especially useful when:

- working with a different language that contains python-fragments that need to be parsed separately and don't have an own file
- generally when python-code needs to be parsed that is not inside a file

**Comment by danielNaczo** [comment]
Done ;)
